### PR TITLE
Add dockerfile to build popular packages

### PR DESCRIPTION
**Pull request by rmcgibbo**
This is just an example, and might not be the optimal configuration for all of the packages.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
The one problem I had is that when I tried to upload to the latest `pip` 8.0 release, it sometimes refuses to download packages because the Python can't verify TLS, so there might be a problem with the Python interpreter we compiled into the docker image, @njsmith.

I suspect the CentOS 5 `openssl-devel` that we used when compiling Python isn't good enough.

```
$ docker run -i -t --rm -v `pwd`:/io quay.io/manylinux/manylinux /bin/bash
WARNING: Error loading config file:stat /home/rmcgibbo/.docker/config.json: permission denied
[root@319449c664ab /]# /opt/3.5/bin/pip install pip --upgrade
Collecting pip
  Downloading pip-8.0.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 418kB/s
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.0.2
[root@319449c664ab /]# /opt/3.5/bin/pip install numpy
Collecting numpy
/opt/3.5.1/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315:
SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication)
extension to TLS is not available on this platform. This may cause the server to present
an incorrect TLS certificate, which can cause validation failures. For more information,
see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
```

**Comment by njsmith** [comment]
Oo, yeah, SNI support is kinda important. I guess this means we should
build our own openssl and point the python configure script at it?

**Comment by rmcgibbo** [comment]
i think so.

**Comment by rmcgibbo** [comment]
I think I will close this PR and make an `example-project` repository or something inside the `manylinux` organization that tries to show an example of our recommended workflow, similar to Olivier's https://github.com/ogrisel/python-appveyor-demo.

**Pull request closed without merging**
