### PR TITLE
Compile Python with latest OpenSSL

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by njsmith** [comment]
Awesome. (And nice one on the use of sha256sum.)

Is there any easy way to test this, do you suppose?

Can you think of any way to reduce the likelihood that wheels will pick up our version of openssl? I would hate to be responsible for a cve because some project carefully built the latest openssl, but then accidentally bundled our version that we had forgotten to update because auditwheel found the wrong one...

**Comment by rmcgibbo** [comment]
I'm testing it now, and trying to get python statically linked to openssl, so then I can delete `libssl.a` afterwards :)

**Comment by rmcgibbo** [comment]
This works nicely now. I've built the image locally and played around with it, and queried `https://www.howsmyssl.com/` from Python, and everything is kosher.

**Comment by njsmith** [comment]
that's so mysterious. you're using a non-standard install location. HOW DOES PYTHON KNOW.

**Comment by rmcgibbo** [comment]
> that's so mysterious. you're using a non-standard install location. HOW DOES PYTHON KNOW.

?

**Comment by rmcgibbo** [comment]
oh, you mean `/usr/local/ssl`?

**Comment by rmcgibbo** [comment]
https://github.com/python/cpython/blob/master/setup.py#L782

**Comment by njsmith** [comment]
Huh. Weird, but convenient!

**Pull request merged**
